[workspace]
resolver = "2"
members = ["everything", "rw_lock", "sync", "async_testing", "kafka", "dynamic-vs-generic", "left-right-map", "serde", "named-tokio-tasks", "arcswap-vs-leftright", "patterns"]
